import 'package:auto_route/auto_route.dart';
import 'package:flutter/material.dart';
import 'package:yalla_agaza/res.dart';
import 'package:yalla_agaza/routers/Router.gr.dart';
import 'package:yalla_agaza/widgets/buttons.dart';
import 'package:yalla_agaza/widgets/centerLogo.dart';
import 'package:yalla_agaza/views/forgetPass/forgetImports.dart';
part 'Login.dart';
part 'LoginData.dart';
