/// Generated by AssetsRefGenerator on 2021/03/23
class Res {

  static const String AC = "assets/photos/AC.png";
  static const String beach1 = "assets/photos/beach1.png";
  static const String car = "assets/photos/car.png";
  static const String cheers = "assets/photos/cheers.png";
  static const String congrat = "assets/photos/congrat.png";
  static const String damals = "assets/photos/damals.png";
  static const String damals2 = "assets/photos/damals2.png";
  static const String facebook = "assets/photos/facebook.png";
  static const String google = "assets/photos/google.png";
  static const String Island = "assets/photos/Island.png";
  static const String logoPk = "assets/photos/logo.jpeg";
  static const String logo = "assets/photos/logo.png";
  static const String logo1 = "assets/photos/logo1.png";
  static const String logo2 = "assets/photos/logo2.png";
  static const String master = "assets/photos/master.png";
  static const String pament = "assets/photos/pament.png";
  static const String Pool = "assets/photos/Pool.png";
  static const String sea = "assets/photos/sea.jpg";
  static const String TV = "assets/photos/TV.png";
  static const String visa = "assets/photos/visa.png";
  static const String wifi = "assets/photos/wifi.png";
}
